name: todo_flutter_mobile_app
description: "A new Flutter project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  flutter_dotenv: ^5.1.0
  formz: ^0.8.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  logger: ^2.4.0
  pinput: ^5.0.0
  intl: ^0.20.2
  flutter_svg: ^2.0.9
  delightful_toast: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/google_logo.svg
